# Generated by Django 5.1.6 on 2025-02-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.parking', verbose_name='Parking'),
        ),
    ]
